logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    org.springframework.boot.actuate: off
    org.springframework.web: debug
    org.springframework.boot: info
    org.springframework.session: debug
    org.springframework.orm.jpa: debug
    org.springframework.transaction: debug
    org.hibernate.SQL: debug
    org.hibernate.type: off
    org.hibernate.tool.schema: error
    com.zaxxer.hikari: error
    io.swagger.models.parameters.AbstractSerializableParameter: error
    io.mustelidae.otter.lutrogale: debug


server:
  error:
    include-stacktrace: always
    whitelabel:
      enabled: true
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
  port: 4210

spring:
  freemarker:
    check-template-location: true
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        use_sql_comments: true
        default_batch_fetch_size: 50
        enable_lazy_load_no_trans: true
        format_sql: true
        dialect:
          storage_engine: innodb
    open-in-view: true


  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 3
      maximum-pool-size: 30
      pool-name: SpirngBootHikariCP
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3319/local?serverTimezone=Asia/Seoul
    username: local
    password: local

  session:
    timeout: 30m
    store-type: jdbc
    jdbc:
      platform: mysql
  web:
    resources:
      add-mappings: false


springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    tagsSorter: alpha